version: '3'
services:
  api:
    container_name: fastapi-server
    build: .
    command: bash -c "export PYTHONPATH=src && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - .env
    ports:
      - '8000:8000'

  redis:
    image: redis
    container_name: redis-server
    expose:
      - 6379